// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2WqduNzJLAhjvBLGR1Xl8bi9L472QxB4',
    appId: '1:1024330857409:web:c8aea91649d1ff49e74d40',
    messagingSenderId: '1024330857409',
    projectId: 'my102-cc981',
    authDomain: 'my102-cc981.firebaseapp.com',
    storageBucket: 'my102-cc981.appspot.com',
    measurementId: 'G-TRD5RG4J4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYoUCXozAliPMTN9bu9V-_CRXZq-NPZhw',
    appId: '1:1024330857409:android:49f2506b14df78f9e74d40',
    messagingSenderId: '1024330857409',
    projectId: 'my102-cc981',
    storageBucket: 'my102-cc981.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYd6Ia-O-qMvnKieG9vG01Y9j-nk1Eons',
    appId: '1:1024330857409:ios:03b3072f661c150fe74d40',
    messagingSenderId: '1024330857409',
    projectId: 'my102-cc981',
    storageBucket: 'my102-cc981.appspot.com',
    androidClientId: '1024330857409-cnnpntiurdqe3o915tbrv30t31la5r8s.apps.googleusercontent.com',
    iosClientId: '1024330857409-35qr4lt6ee6es6muv2dv2rm70nrkoi7f.apps.googleusercontent.com',
    iosBundleId: 'com.hkacc102.my102',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYd6Ia-O-qMvnKieG9vG01Y9j-nk1Eons',
    appId: '1:1024330857409:ios:03b3072f661c150fe74d40',
    messagingSenderId: '1024330857409',
    projectId: 'my102-cc981',
    storageBucket: 'my102-cc981.appspot.com',
    androidClientId: '1024330857409-cnnpntiurdqe3o915tbrv30t31la5r8s.apps.googleusercontent.com',
    iosClientId: '1024330857409-35qr4lt6ee6es6muv2dv2rm70nrkoi7f.apps.googleusercontent.com',
    iosBundleId: 'com.hkacc102.my102',
  );
}
